favicon: images/avatar.png

menu:
  Home: /
  About: about

copyright:
  name: terry

license:
  name: CC-BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

rss:
  path: atom.xml

mathjax:
  enable: false

katex:
  enable: true

utterances:
  enable: true
  repo: owner/repo
  issueTerm: pathname
  theme: github-light

analytics:
  enable: false
  gtag: G-77E699FP7J